spring:
  application:
    name: devica

  profiles:
    default: local

  flyway:
    enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never

management:
  endpoint:
    health:
      probes:
        enabled: true
        add-additional-paths: true
      group:
        readiness:
          include: readinessState, db
  metrics:
    distribution:
      slo:
        http.server.requests: 100ms, 300ms, 500ms, 1s, 2s, 5s
