package com.wrb.devica.probe.event;

public enum ExperimentEventName {
    RECOMMENDATION_STARTED,
    QUESTION_VIEWED,
    QUESTION_ANSWERED,
    ANSWER_CHANGED,
    SPEC_ADJUSTED,
    RECOMMENDATION_COMPLETED,
    FINAL_SPEC_EDITED,
    FIT_FEEDBACK_SUBMITTED,
    UNDERSTANDING_FEEDBACK_SUBMITTED,
    PRODUCT_LIST_VIEWED,
    PRODUCT_CLICKED
}
